### PR TITLE
Bookstore: connect to API

### PR DESCRIPTION
**Pull request by MostafaShahat2021**
## In this PR:
- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that I used the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
 - Make sure that I documented my work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
 - Follow Microverse's list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
 - ⭐️use the [Bookstore API](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) as backend.
 - ⭐️Use [axios](https://axios-http.com/docs/intro) with [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) to make HTTP requests to the backend.
 - ⭐️Fetch books from the Bookstore API after the component has rendered.
 - ⭐️ Refactor add book and remove book features to persist user changes in the server.

### CODE REVIEW

**Review by Munsa1 — CHANGES_REQUESTED** [review]
Hi @MostafaShahat2021, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Technical Aspect Of Project Is Done Well :heavy_check_mark: 
Clean Codebase :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
### Due to insufficient files changed
- [x] Please remove the link to the `Live Demo` section for a more professional readme file as it is a link to the section which does not exist making it broken.
image

- [x] Kindly remove the link to the `install` part of your `Getting Started` section, as it points to a part that has been removed.
image

- [x] Also think about fixing the link to the `deployment` sub-section in the table of contents under the `Getting Started` section. clicking on it should take the user to that part of the readme file
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MostafaShahat2021** [comment]
Hi @Munsa1 👋, Thanks for your suggestions, I'll fix that.

**Review by Reem-lab — APPROVED** [review]
# Hi @MostafaShahat2021, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights

- [x]  Followed Gitflow 💯
- [x]  Descrtipive PR⭐
- [x] Kudos for working on connecting with API🤩
- [x] No Linters error ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MostafaShahat2021** [comment]
Hi @Reem-lab 👋 , Thanks a lot 💯 for your efforts in reviewing my code, I really appreciate it 😄 .

**Pull request merged**
